import mysql.connector
from mysql.connector import errorcode

config = {
    "user": "pysports_user",
    "password": "P@ssw0rd",
    "host": "3306",
    "database": "pysports",
    "raise_on_warnings": True
}